core/accounts/urls.py
from django.urls import path
from .views import SignUpPageView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpPageView.as_view(), name='signup'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [

    #django admin
    path('admin/', admin.site.urls),
    #user management
    path('accounts/', include("django.contrib.auth.urls")),
    #local apps
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include('pages.urls', namespace='pages')),
    
] 

core/pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path("",HomePageView.as_view(), name='home'),
    path("about/",AboutPageView.as_view(), name='about'),
    path("contact/",ContactPageView.as_view(), name='contact'),
]

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

core/pages/models.py
from django.db import models

# Create your models here.

core/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm





class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

core/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms  import CustomUserCreationForm

class SignUpPageView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

core/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView




class HomePageView(TemplateView):
    template_name = 'pages/home.html'

class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

class ContactPageView(TemplateView):
    template_name = 'pages/contact.html'

core/templates/_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Bookstore{% endblock title %}</title>
    <header>
        <a href="{% url 'pages:home' %}">home</a>
        
        {% if not  user.is_authenticated %}
            <a href="{% url 'login' %}">login</a>
    </hr>
            <a href="{% url 'accounts:signup' %}">sign up</a>
        {% else %}
            <a href="{% url 'logout' %}">log out </a>
        {% endif %}
    </header>
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

</body>

</html

core/templates/pages/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>about us</title>
</head>
<body>
    <h2>this is about</h2>
</body>
</html>

core/templates/pages/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact us</title>
</head>
<body>
    <h3 style="color: blue;">this is contact</h3>
</body>
</html>

core/templates/pages/home.html
{% extends "_base.html" %}

{% block content %}
    <h1 style="color: crimson;">hello to  yoou main page </h1>
{% endblock content %}